### ISSUE TITLE
Link to original BOLTS website in README is dead

### ISSUE THREAD

**Issue by normandc** [boltsparts/BOLTSFC#1]
Looks like bolts-library.org is no longer active, even if the domain is still registered. The last available snapshot on archive.org is from July 19, 2017. https://web.archive.org/web/20170719105944/http://www.bolts-library.org/en/index.html

Maybe it would be a good idea to extract available documentation and create a wiki in your Git repo. Not sure if it should go in the package repo or the boltsdev repo.

**Comment by berndhahnebach** [comment]
Hi Norm,

see https://forum.freecadweb.org/viewtopic.php?f=8&t=4549&start=280#p194852 That would be a good idea. I have been trying to contact the old maintainer but got no answer. It is like Jürgen in FreeCAD, he has left his project. As far as I know all the webpage is on the BOLTS github, but I have no clue how to make a web page out of this. https://github.com/jreinhardt/BOLTS/tree/master/website

cheers bernd

**Comment by normandc** [comment]
Looked at it, doesn't seem to be run-of-the-mill CMS stuff...

BTW he replied to an issue on that repo last October... https://github.com/jreinhardt/BOLTS/issues/176

**Comment by normandc** [comment]
Well, docs are in Markdown, which is the format for Github's wiki system, in theory it should only be a matter of creating wiki pages and pasting the content in them, plus copying images and fixing links I guess. Here are the source docs for v0.4, I suppose that's the version you're using?

https://github.com/jreinhardt/BOLTS/tree/master/website/docs/sources/0.4

https://github.com/jreinhardt/BOLTS/tree/master/website/docs/sources/0.4

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=8&t=30668&start=10#p308558 Even the original website is online again :+1:
