### ISSUE TITLE
uic import failed on ubuntu

### ISSUE THREAD

**Issue by LuisLlana** [boltsparts/BOLTSFC#27]
Hello,
  I have just installed the BOLTSFC macros in freecad using the macros manager. When I try to start the macro I obtain the following error:
```
uic import failed. Make sure that the pyside tools are installedTraceback (most recent call last):
  File "/home/luis/.FreeCAD/Macro/start_bolts.FCMacro", line 1, in <module>
    import BOLTS
  File "/home/luis/.FreeCAD/Mod/BOLTSFC/BOLTS/__init__.py", line 44, in <module>
    from .gui import freecad_bolts as boltsgui
  File "/home/luis/.FreeCAD/Mod/BOLTSFC/BOLTS/gui/freecad_bolts.py", line 30, in <module>
    Ui_BoltsWidget,QBoltsWidget = uic.loadUiType(join(bolts_path,'bolts_widget.ui'))
  File "<string>", line 1, in <module>pysideuic
<class 'ModuleNotFoundError'>: No module named 'pysideuic'
```

I am running freecad in Ubuntu 20.04. I have tried `pip install pysideuic` and `python2 -m pip install pysideuic` with no success.

**Comment by berndhahnebach** [comment]
either the workaround from https://github.com/boltsparts/BOLTSFC/issues/28 or the installation from https://forum.freecadweb.org/viewtopic.php?f=4&t=51324 should work.

Would you give some feedback?

**Comment by berndhahnebach** [comment]
Did you get it working?

**Comment by berndhahnebach** [comment]
https://github.com/boltsparts/BOLTSFC/issues/40
