### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by PascalMF** [boltsparts/BOLTSFC#29]
I just installed BOLTS on my MAC in FreeCAD.  I'm not a programmer and not vert computer savy.  After having installed Bolts, executed the Macro and made a custom Tool bar bottom, the Report view is telling me:
<class 'SyntaxError">: Missing parentheses in call to 'print'. Did you mean print(Label Name")? (_init_.py line 83)

Some one have some incite?

**Comment by berndhahnebach** [comment]
transfered to BOLTSFC
